### PR TITLE
docs: improve + simplify

### PR DESCRIPTION
**Pull request by uncenter**

### CODE REVIEW

**Comment by uncenter** [comment]
Most of the files changed are just from running `deno fmt`, which I assume is the formatter I should be using here. I also updated and renamed the first "core" or "root" pages, but I couldn't figure out how to order them in the left panel.

**Comment by uncenter** [comment]
I'm not a Lume user but is there a better theme we can use? I'm finding the current one a little lacking in features and aesthetic and difficult to customize - can we just pull the theme (https://github.com/lumeland/theme-simple-wiki) into here entirely to make it easier to make changes?

**Comment by oscarotero** [comment]
Thank you!
I don't want to create a website for the documentation for now. And I like the documentation to be a directory with plain markdown files, so they can be used not only to build the site but also to read directly from GitHub and similar.

Is true that the theme doesn't allow to order the elements in the menu (they are sorted by url). I'll include an option for that.

**Comment by uncenter** [comment]
> Thank you! I don't want to create a website for the documentation for now. And I like the documentation to be a directory with plain markdown files, so they can be used not only to build the site but also to be read directly from GitHub and similar.
> 
> Is true that the theme doesn't allow to order the elements in the menu (they are sorted by url). I'll include an option for that.

Great. Do you want (me) to remove the Lume config in `docs/` so its just markdown in there?

**Comment by uncenter** [comment]
Sorry I misunderstood- @oscarotero are you saying the current site *is not* a documentation website? I'm confused. Do you want `docs/` to just be markdown files linked to in the README? What goes on the website, if anything?

**Comment by oscarotero** [comment]
Sorry, I didn't explain myself very well :)

There's a documentation site (https://vento.js.org/) but I don't want to design a different website or including all stuff (css files, templates, etc) inside this repo. I like the documentation in this repo is only markdown files, so it's independent of the existing website.

The `_config.ts` is needed by Lume to build the website, so it cannot be deleted.

I'll try to improve the current theme to allow to configure the order of the elements in the navbar.

**Comment by uncenter** [comment]
> Sorry, I didn't explain myself very well :)
> 
> There's a documentation site ([vento.js.org](https://vento.js.org/)) but I don't want to design a different website or including all stuff (css files, templates, etc) inside this repo. I like the documentation in this repo is only markdown files, so it's independent of the existing website.
> 
> The `_config.ts` is needed by Lume to build the website, so it cannot be deleted.
> 
> I'll try to improve the current theme to allow to configure the order of the elements in the navbar.

Ah okay gotcha. In that case I can help make a few PRs for the current theme in that repo. Thanks for clearing it up!

**Pull request merged**
